config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#index'

  # devise_for :admins, controllers: { sessions: 'admins/sessions',
  #          registrations: 'admins/registrations' }

  # devise_for :professionals, controllers: { sessions: 'professionals/sessions',
  #                                         registrations: 'professionals/registrations' }

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations' }

  resources :tenants
  resources :proprietors
  resources :homes do
    resources :appointments
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def index
    if user_session
      @proprietor = current_user.proprietor
      @homes = @proprietor.homes.all if @proprietor.present?
    end
  end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/views/static_pages/_admin.html.erb
<% if admin_signed_in? %>

  <%= link_to 'espace', proprietors_path %>

<% end %>




<h2>Admin</h2>

<% if admin_signed_in? %>
  <div>
    Logged in as <strong><%= current_admin.email %></strong>.
    <%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_admin_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_admin_session_path, :class => 'navbar-link'  %>
  </div>
<% end %>

<br>
<hr>
<br>

<br>

<h2>Professional</h2>

<% if professional_signed_in? %>
  <div>
    Logged in as <strong><%= current_professional.email %></strong>.
    <%= link_to 'Edit profile', edit_professional_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_professional_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_professional_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_professional_session_path, :class => 'navbar-link'  %>
  </div>
<% end %>



<br>

<%= render 'admin' %>

app/views/static_pages/_navbar.html.erb
  <nav class="navbar navbar-default navbar-fixed-top animated fadeInDown" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span>Show Menu</span>
        </button>
        <a class="navbar-brand" >HomeLockup</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse" id="CollapseMenu">
        <ul class="nav navbar-nav navbar-right">
          <li class="about-nav"><a href="#"><i class="fa fa-fw fa-user-o" aria-hidden="true"></i> About</a></li>
          <li><i class="fa fa-fw fa-code" aria-hidden="true"></i>
            <% if user_signed_in? %>
                Logged in as <strong><%= current_user.email %></strong>.
                <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
            <%end %>
          </li>
          <li class="contact-nav"><a href="#"><i class="fa fa-fw fa-envelope-o" aria-hidden="true"></i> Contact</a></li>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
  </nav>

app/views/static_pages/_user.html.erb
<% if user_signed_in? %>
  <%if user_session %>

  <% if @proprietor.present?%>

          <h3>tu es un Proprietaire</h3>
          <% link_to 'Espace le proprietaire', proprietor_path(@proprietor.id), style: "margin-left: 40%" %>
          <br>
        <%else %>
          <% link_to 'Cree le proprietaire', new_proprietor_path, style: "margin-left: 40%" %>
    <%end %>
  <%end %>
          <hr>


  <% if current_user.tenant.present?%>

        <h3>tu es un Locataire</h3>
        <%= link_to 'Espace le locataire', tenant_path(current_user.tenant.id), style: "margin-left: 40%" %>
        <br>

    <hr>
  <% @homes.each do |f| %>
    <% if f.online %>
    <%= f.name %>
    <%= f.description %>
      <br>
    <%end %>
    <%end %>

  <%else %>
        <%= link_to 'Cree le locataire', new_tenant_path, style: "margin-left: 40%" %>
        <hr>
  <%end %>


<%end %>

app/views/static_pages/index.html.erb
<header>
  <!-- HEADER CONTENT STARTS HERE -->
  <div class="header-content" id="start-navbar-dark">

    <div class="container-fluid">
      <div class="row  about-section">
        <!-- BEGIN SECTIONS -->
        <div class="col-md-12 col-lg-6">
          <% if user_signed_in? %>
            <%if user_session %>
              <div  class="profilepic">
                <% if @proprietor.present?%>
                  <%= link_to 'Espace le proprietaire', proprietor_path(@proprietor.id) %><br>
                  <%= link_to 'ajouter une Maison', new_home_path%><br>
                  <% if @homes.present? %>
                    <%= link_to 'Espace Maison', homes_path%><br>
                  <%end %>
                <%else %>
                  <%= link_to 'Cree le proprietaire', new_proprietor_path  %>
                <%end %>
                <!-- PROPRIETOR-->
              </div>
              </div>
              <% if @proprietor.present?%>
                <div class="col-md-12 col-lg-6 about">
                  <h3 id="start-about-animation"><i class="fa fa-handshake-o" aria-hidden="true"></i><%= current_user.email %></h3>
                  <p class="tagline">phone: <%=@proprietor.phone%></p>
                  <p class="tagline">address: <%=@proprietor.address%><br>
                    <!--<p class="desc-start"><br>-->
                    <%@proprietor.address %></p>
                  <p> <% if @homes.present? %>
                    <ul><% @homes.each do |f| %>
                        <li>  <%= f.name %></li><br>
                        <li> <%= f.description %></li><br>
                        <li>  <%= link_to'ajouter une reservation', new_home_appointment_path(f.id) %></li>
                        <li>  <%= link_to'voir les reservations',   home_appointments_path(f.id) %></li>
                        <hr>
                      <% end %>
                    </ul>
                  <%end %>
                <%end %>
              <%end %>
            <%end %>
          </div>
          </div>

    </div>
    <button class="animated swing about-nav">About Me</button>
  </div>
</header>
<%= render 'user' %>







  <section class="row contact">
    <div class="col-sm-12 col-md-6">
      <div class="contact-content">
        <h3>Let's Get In Touch!</h3>
        <p><a href="https://www.github.com/Wheatability"><i class="fa fa-github"></i>GitHub</a></p>
        <p><a href="https://www.linkedin.com/in/tpurvines"><i class="fa fa-linkedin"></i>Linked In</a></p>
        <p><a href="https://codepen.io/Wheatability/"><i class="fa fa-codepen"></i>Codepen</a></p>
        <p><a href="mailto:tylerpurvines@gmail.com"><i class="fa fa-envelope"></i>Email</a></p>
      </div>
    </div>
    <div class="col-md-6">
    </div>
  </section>
  <section class="row creator">
    <div class="col-sm-12">
      <p>Page <i class="fa fa-code"></i> with <i class="fa fa-heart"></i> by belette06</p>
    </div>
  </section>
  <!-- END SECTIONS -->
</div>