config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#index'

  # devise_for :admins, controllers: { sessions: 'admins/sessions',
  #          registrations: 'admins/registrations' }

  # devise_for :professionals, controllers: { sessions: 'professionals/sessions',
  #                                         registrations: 'professionals/registrations' }

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations' }

  resources :tenants
  resources :proprietors
  resources :homes do
    resources :appointments
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/home.rb
# frozen_string_literal: true

class Home < ApplicationRecord

  has_many :appointments
  has_many :tenants, through: :appointments
  accepts_nested_attributes_for :tenants

end

app/controllers/homes/tenant_homes_controller.rb
# frozen_string_literal: true

    class Homes::TenantHomesController < ApplicationController


      def index
        @home = Home.find(params[:format])
        @tenant_homes = @home.tenant_homes
      end

      def show
        @home = Home.where(params[:home_id])
        @tenant_home = TenantHome.find(params[:id])
      end

      def edit
        @tenant_home = TenantHome.find(params[:id])
      end

      def new
        @tenant_home =  TenantHome.new
        @tenant_home.tenant = Tenant.new
      end

      def create
        @tenant_home = TenantHome.new
        @tenant_home.home_id = @home.id
        @tenant_home.tenant = Tenant.new
        @tenant_home.tenant.save(params_tenant_home)
        @tenant_home.tenant_id = @tenant_home.tenant.id

        if @tenant_home.save
          redirect_to @tenant_home
        end
      end

      def update
        @tenant_home = TenantHome.find(params[:id])
        if @tenant_home.update(params_tenant_home)
          redirect_to homes_tenant_home_path(@tenant_home.id), notice: 'tenant_home was successfully updated.'
        else
          render :edit
        end
      end

      def destroy
        @tenant_home = TenantHome.find(params[:id])
        @tenant_home.delete(params_tenant_home)
        redirect_to homes_tenant_homes_path, notice: 'tenant_home was successfully destroyed.'
      end

      private

      # require 'pry', <%=binding.pry %>
      def save_homes

      end

      def params_tenant_home
        params.require(:tenant_home).permit(:home_id, :tenant_id)
      end
    end

app/controllers/homes_controller.rb
# frozen_string_literal: true

class HomesController < ApplicationController
  before_action :set_homes, only: %i[show update edit destroy]

  def index
    @proprietor = current_user.proprietor
    @homes = @proprietor.homes
  end

  def show; end

  def new
    @home = Home.new
  end

  def create
    @proprietor = current_user.proprietor
    @home = @proprietor.homes.build(params_homes)
    if @home.save
      redirect_to @home, notice: 'Home create'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @home.update(params_homes)
      redirect_to @home, notice: 'updated..'
    else
      render :edit
    end
  end

  def destroy
    if @home.delete
      redirect_to @home, notice: 'destroy..'
    end
  end

  private

  def params_homes
    params.require(:home).permit(:name, :description, :online, :proprietor)
  end

  def set_homes
    @home = Home.find(params[:id])
  end
end

app/helpers/homes_helper.rb
# frozen_string_literal: true

module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_with model: @home do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name%>
<br>
  <%= f.label :description %>
  <%= f.text_field :description%>
  <br>
  <%= f.label :Online %>
  <%= f.check_box :online, {},  "true", "false" %>

  <br>
  <%= f.submit %>

<% end %>

app/views/homes/edit.html.erb
<h1>Homes#edit</h1>
<p>Find me in app/views/homes/edit.html.erb</p>

<%= render 'form' %>

app/views/homes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>HOMES #show</h1>

<table>
  <thead>
  <tr>
    <th>Home</th>
    <th colspan="2"></th>
  </tr>
  </thead>

  <tbody>
  <% @homes.each do |home| %>
    <tr>
      <td>__Name__</td>
      <td>__Description__</td>
      <td>__Online__</td>
    </tr>
    <tr>
      <td>|<%= home.name %></td>|
      <td>|<%= home.description %></td>|
      <td>|<%if  home.online == true %>
          <%=  "Home is Online"  %>
        <%else %>
          <%=   "Home is Offline" %>
        <%end %></td>
      <td>|
      <td>
        <%= link_to 'Show', home %><br/>
        <%= link_to 'Edit',  edit_home_tenant_home_path(home.id) %><br/>
        <%= link_to 'Destroy',  home_tenant_home_path(home.id), method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>

  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'new Home', new_home_tenant_home_path %><br/>
<%= link_to 'Landing page', root_path %>


%>

app/views/homes/new.html.erb
<h1>Homes#new</h1>
<p>Find me in app/views/homes/new.html.erb</p>

<%= render "form" %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<h1>HOMES #show</h1>
<table>
  <tbody>
    <tr>
      <td><%= @home.name %></td>
      <td><%= @home.description %></td>
      <td>
        <%if  @home.online == true %>
          <%= "Home is Online"  %>
        <%else %>
          <%= "Home is Offline" %>
        <%end %>
      </td>
      <td><%= link_to 'index', home_appointments_path(@home.id) %></td>
      <td><%= link_to 'Edit',  edit_home_appointment_path(@home.id) %></td>
      <td><%= link_to 'Destroy', @home, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  </tbody>
</table>

<br>

<%= link_to 'Landing page', root_path %>