config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#index'

  # devise_for :admins, controllers: { sessions: 'admins/sessions',
  #          registrations: 'admins/registrations' }

  # devise_for :professionals, controllers: { sessions: 'professionals/sessions',
  #                                         registrations: 'professionals/registrations' }

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations' }

  resources :tenants
  resources :proprietors
  resources :homes do
    resources :appointments
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/proprietor.rb
# frozen_string_literal: true

class Proprietor < ApplicationRecord
  belongs_to :user, class_name: 'User'

  has_many :homes
  accepts_nested_attributes_for :homes
end

app/controllers/proprietors_controller.rb
# frozen_string_literal: true

class ProprietorsController < ApplicationController
  before_action :set_proprietor, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @proprietors = Proprietor.all
  end

  def new
    @proprietor = Proprietor.new
    # @proprietor = current_user.proprietor.build_user
  end

  def show
    # @proprietor = current_user.proprietor.build_user
  end

  def create
    @proprietor = Proprietor.new(params_proprietor)
    # @proprietor.user.id = current_user.id
    # @proprietor = current_user.build_proprietor(params_proprietor)
    @proprietor.user = current_user
    if @proprietor.save(params_proprietor)
      redirect_to root_path, notice: 'Proprietor was successfully create.'
    else
      render :edit
      end
   end

  def edit; end

  def update
    if @proprietor.update(params_proprietor)
      redirect_to @proprietor, notice: 'Proprietor was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    set_proprietor
    if @proprietor.delete
      redirect_to @proprietor, notice: 'Proprietor was successfully destroy.'
    else
      render :edit
    end
  end

  private

  def params_proprietor
    params.require(:proprietor).permit(:phone, :address, :user)
  end

  def set_proprietor
    @user = current_user
    @proprietor = @user.proprietor
  end
end

app/helpers/proprietors_helper.rb
# frozen_string_literal: true

module ProprietorsHelper
end

app/views/proprietors/_form.html.erb
<%= form_with model: @proprietor do |f| %>

  <%= f.label :phone %>
  <%= f.text_field :phone%>
  <br>
  <%= f.label :address %>
  <%= f.text_field :address%>

  <%= f.submit %>

<% end %>

app/views/proprietors/edit.html.erb
<h1>Proprietors#update</h1>
<p>Find me in app/views/proprietors/update.html.erb</p>

<%= render 'form' %>

<br>
<br>
<%= link_to 'Landing page', root_path %>

app/views/proprietors/index.html.erb
<h1>Proprietors#index</h1>
<p>Find me in app/views/proprietors/index.html.erb</p>

<%@proprietors.each do |f| %>
  <%=f.id %><br>
  <%=f.address %><br>
  <%=f.phone %><br>
  <%=link_to 'edit', edit_proprietor_path(@proprietors) %><br>
  <%=link_to "delete",  proprietor_path(@proprietors), method: :delete, class: 'btn', data: { confirm: 'Are you sure?' } %>
  <hr>
<% end %>

<hr>
<%= link_to 'Menu', root_path %><br>
<%= link_to 'New', new_proprietor_path %>
<hr>

app/views/proprietors/new.html.erb
<h1>Proprietors#new</h1>
<p>Find me in app/views/proprietors/new.html.erb</p>

<%= render 'form' %>

app/views/proprietors/show.html.erb
<h1>Proprietors#show</h1>
<p id="notice"><%= notice %></p>
<p>
  <b>title:</b>
  <%= current_user.proprietor.phone %>
</p>

<p>
  <b>bio:</b>
  <%= current_user.proprietor.address %>
</p>


<%= link_to 'Edit', edit_proprietor_path(current_user.proprietor.id) %>

<%= link_to 'delete', proprietor_path(current_user.proprietor.id), method: :delete %>
<br>
<br>
<br>
<%= link_to 'Landing page', root_path %>